# Load trained models

> use this notebook to check the correctness of tained models

In [1]:
job_dir = "gs://mlteam-ml-specialization-2021-blackfriday/aiplatform_jobs/bf_20210426_145558/"

In [2]:
from os.path import join

scann_path = join(job_dir, "Scann")

## Load Scann

In [3]:
import tensorflow as tf
import tensorflow_recommenders as tfrs # requirea to load SCANN
scann_loaded = tf.keras.models.load_model(scann_path)

In [4]:
scann_example = {  # used to check scann consistency
    "Gender": tf.constant(["M"]),
    "Age": tf.constant(["26-35"]),
    "Occupation": tf.constant(["0"]),
    "City_Category": tf.constant(["B"]),
    "Stay_In_Current_City_Years": tf.constant(["4+"]),
    "Marital_Status": tf.constant(["0"]),
}


In [5]:
scann_results = scann_loaded(scann_example)  # prediction required to store the model

In [12]:
scann_results

(<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
 array([[3.1140285, 3.0735807, 2.8716292, 2.8528547, 2.7234626, 2.7076268,
         2.689435 , 2.6258552, 2.6027102, 2.5738482]], dtype=float32)>,
 <tf.Tensor: shape=(1, 10), dtype=string, numpy=
 array([[b'P00284342', b'P00223342', b'P00162542', b'P00363342',
         b'P00204942', b'P00292342', b'P00133642', b'P00028342',
         b'P00046542', b'P00279142']], dtype=object)>)

### Check if the prediction match:

In [17]:
!gsutil cat $"{job_dir}"params.json

{
    "train_path": "gs://mlteam-ml-specialization-2021-blackfriday/dataset/parsed/202104130952/train.csv",
    "test_path": "gs://mlteam-ml-specialization-2021-blackfriday/dataset/parsed/202104130952/test.csv",
    "job_dir": "gs://mlteam-ml-specialization-2021-blackfriday/aiplatform_jobs/bf_20210426_145558",
    "n_epochs": 20,
    "embedding_dim": 32,
    "batch_size": 128,
    "learning_rate": 0.01,
    "product_id_col_name": [
        "Product_ID"
    ],
    "user_features": [
        "Gender",
        "Age",
        "Occupation",
        "City_Category",
        "Stay_In_Current_City_Years",
        "Marital_Status"
    ],
    "scann_shape": "(3601,)",
    "scann_example": "{'Gender': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'M'], dtype=object)>, 'Age': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'26-35'], dtype=object)>, 'Occupation': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'0'], dtype=object)>, 'City_Category': <tf.Tensor: shape=(1,), dtype=string